[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="page" type="co.yiiu.core.bean.Page" --]
[#-- @ftlvariable name="site" type="co.yiiu.config.properties.SiteConfig" --]
[#-- @ftlvariable name="model" type="co.yiiu.core.base.BaseEntity" --]
[#-- @ftlvariable name="topic" type="co.yiiu.module.topic.pojo.Topic" --]
[#-- @ftlvariable name="user" type="co.yiiu.module.user.pojo.User" --]
[#-- @ftlvariable name="comment" type="co.yiiu.module.comment.pojo.Comment" --]
[#-- @ftlvariable name="sec" type="co.yiiu.config.SecurityTag" --]
[#-- @ftlvariable name="log" type="co.yiiu.module.log.pojo.Log" --]
[#-- @ftlvariable name="tag" type="co.yiiu.module.tag.pojo.Tag" --]