[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="page" type="org.springframework.data.domain.Page" --]
[#-- @ftlvariable name="site" type="co.yiiu.config.SiteConfig" --]
[#-- @ftlvariable name="model" type="co.yiiu.core.base.BaseEntity" --]
[#-- @ftlvariable name="topic" type="co.yiiu.module.topic.model.Topic" --]
[#-- @ftlvariable name="user" type="co.yiiu.module.user.model.User" --]
[#-- @ftlvariable name="comment" type="co.yiiu.module.comment.model.Comment" --]
[#-- @ftlvariable name="sec" type="co.yiiu.config.SecurityConfig" --]
[#-- @ftlvariable name="log" type="co.yiiu.module.log.model.Log" --]
[#-- @ftlvariable name="tag" type="co.yiiu.module.tag.model.Tag" --]