package co.yiiu.module.topic.mapper;

import co.yiiu.module.topic.pojo.Topic;
import co.yiiu.module.topic.pojo.TopicWithBLOBs;

public interface TopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    int insert(TopicWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    int insertSelective(TopicWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    TopicWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    int updateByPrimaryKeySelective(TopicWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(TopicWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    int updateByPrimaryKey(Topic record);
}