[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="sec" type="co.yiiu.pybbs.config.ShiroTag" --]
[#-- @ftlvariable name="model" type="co.yiiu.pybbs.util.BaseModel" --]
[#-- @ftlvariable name="i18n" type="co.yiiu.pybbs.util.LocaleMessageSourceUtil" --]
