package co.yiiu.module.topic.pojo;

public class TopicWithBLOBs extends Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.content
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.down_ids
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private String downIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.up_ids
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private String upIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.content
     *
     * @return the value of topic.content
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.content
     *
     * @param content the value for topic.content
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.down_ids
     *
     * @return the value of topic.down_ids
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public String getDownIds() {
        return downIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.down_ids
     *
     * @param downIds the value for topic.down_ids
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setDownIds(String downIds) {
        this.downIds = downIds == null ? null : downIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.up_ids
     *
     * @return the value of topic.up_ids
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public String getUpIds() {
        return upIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.up_ids
     *
     * @param upIds the value for topic.up_ids
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setUpIds(String upIds) {
        this.upIds = upIds == null ? null : upIds.trim();
    }
}