package co.yiiu.module.topic.pojo;

import java.util.Date;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.comment_count
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.down
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private Integer down;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.good
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private Boolean good;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.in_time
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private Date inTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.last_comment_time
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private Date lastCommentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.modify_time
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.tag
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.top
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private Boolean top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.up
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private Integer up;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.user_id
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.view
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private Integer view;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.weight
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    private Double weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.comment_count
     *
     * @return the value of topic.comment_count
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.comment_count
     *
     * @param commentCount the value for topic.comment_count
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.down
     *
     * @return the value of topic.down
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public Integer getDown() {
        return down;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.down
     *
     * @param down the value for topic.down
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setDown(Integer down) {
        this.down = down;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.good
     *
     * @return the value of topic.good
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public Boolean getGood() {
        return good;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.good
     *
     * @param good the value for topic.good
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setGood(Boolean good) {
        this.good = good;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.in_time
     *
     * @return the value of topic.in_time
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.in_time
     *
     * @param inTime the value for topic.in_time
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.last_comment_time
     *
     * @return the value of topic.last_comment_time
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public Date getLastCommentTime() {
        return lastCommentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.last_comment_time
     *
     * @param lastCommentTime the value for topic.last_comment_time
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setLastCommentTime(Date lastCommentTime) {
        this.lastCommentTime = lastCommentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.modify_time
     *
     * @return the value of topic.modify_time
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.modify_time
     *
     * @param modifyTime the value for topic.modify_time
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.tag
     *
     * @return the value of topic.tag
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.tag
     *
     * @param tag the value for topic.tag
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.top
     *
     * @return the value of topic.top
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public Boolean getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.top
     *
     * @param top the value for topic.top
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setTop(Boolean top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.up
     *
     * @return the value of topic.up
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public Integer getUp() {
        return up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.up
     *
     * @param up the value for topic.up
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setUp(Integer up) {
        this.up = up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.user_id
     *
     * @return the value of topic.user_id
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.user_id
     *
     * @param userId the value for topic.user_id
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.view
     *
     * @return the value of topic.view
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public Integer getView() {
        return view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.view
     *
     * @param view the value for topic.view
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setView(Integer view) {
        this.view = view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.weight
     *
     * @return the value of topic.weight
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.weight
     *
     * @param weight the value for topic.weight
     *
     * @mbggenerated Mon Jul 23 13:51:45 CST 2018
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }
}